### ISSUE TITLE
[Bug] Mod sometimes doesn't recognize passing a ring, and breaks

### ISSUE THREAD

**Issue by Hinalover** [teelolws/Dragonriding_Speedrun#3]
While doing the Outland Cup, I noticed that the mod will sometimes break when it doesn't register a ring was passed through and will continue to act like I missed the ring. This usually happens due to hit box of the ring being larger than the ring itself. Thus, you can be slightly outside the ring, and still be counted as going through the ring. But the mod would not register the trigger. Still the bug only sporatically happened after all 30 routes in the Outland Cup (5-10 times over 4-6 hours).

**Comment by teelolws** [comment]
Can you tell me which race and difficulty? I could have recorded its ring location slightly incorrectly, and can go back and recheck.

**Comment by Hinalover** [comment]
Hard to say where exactly it happened. I remember happening on the reverse course of Eco-Dome Excursion (mod said it was something at -32 seconds or something when I finished the race).

The other I remember happening was advance Fel Pit Fracas; I WANT to say it was during the last bend before going up and getting to the end of the run.

**Comment by teelolws** [comment]
Okay, I've rerecorded the coordinates for those two races in https://github.com/teelolws/Dragonriding_Speedrun/commit/4fde65ab88c93c4e0d25caa665b7632db0dcd0f4 and https://github.com/teelolws/Dragonriding_Speedrun/commit/b1f4cebbc7f69404b5d91e2128a67d310ed2d912

Some of the coordinates were slightly out of an acceptable range which probably caused that issue. If you ever spot this issue again, let me know the race and difficult so I can check the waypoints more accurately. The Outland Cup ones were all recorded in a rush to get the patch out ASAP.
